### ISSUE TITLE
Logic operations

### ISSUE THREAD

**Issue by ost-ing** [mnemonicdevices/md001#17]
**Is your feature request related to a problem? Please describe.**
As a user I want to create logical relationships between channels

**Describe the solution you'd like**
Add a logic unit, that allows various logic operands to be applied between channels

**Describe alternatives you've considered**
Using a square wave and amplitude modulation, a person can somewhat simulate an AND logic operation, but this isn't the most expressive and intuitive way

**Potential ramifications or implications**
A logical threshold will likely be required, as is with the Sample & Hold unit
 
**Additional context**
N/A

**Comment by CBluesF** [comment]
"Analogue" logic would also be a really nice addition, i.e. Min/Max

**Comment by ost-ing** [comment]
@CBluesF thanks for the suggestion,
I've now added `min` `max` `avg` `add` `sub` `not` `or` and `and`.

For `not` `or` and `and`, a threshold value is used to determine the outcome, e.g. for `or`, if either CH1 or CH2 are above the threshold the signal is rendered, otherwise 0V.

This is added in 0.6.0
