### ISSUE TITLE
Encoder Acceleration

### ISSUE THREAD

**Issue by fourhexagons** [mnemonicdevices/md001#25]
**Problem**
When turning the encoder through large value ranges (such as LFO phase), it can take a lot of turns to get to the desired value.

**Solution**
Implementing acceleration on the encoder would help users more quickly traverse large value ranges.

**Alternatives**
N/A

**Implications**
Getting the acceleration curve adjusted would be the challenge as too low and it's still slow, while too high and it could be difficult to land on the desired value.
 
**Additional context**
N/A

**Comment by ost-ing** [comment]
User feedback suggested to use `HOLD SELECT` + `ENCODER ROTATE` to achieve this. I think this would work well. I just want to make sure that this combination doesn't impact anything else.

I've assigned it to the 0.4.0 release.
