### ISSUE TITLE
Save/Load Preset Function

### ISSUE THREAD

**Issue by FutureErik** [mnemonicdevices/md001#26]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Beeing able to save the current settings of all channels as a preset to the SD card would be nice. Loading a preset should be possible on the Juniper for fast access to different presets. This would enable us to manage, backup and share presets.

**Potential ramifications or implications**
- Loading will probably require a reboot. Either way, on the fly loading would cause jumps in CV levels at the transition point.
- Menus could be placed in system sub menu.
- Maybe save the settings from global menu in the preset as well.
- Saving of recorder state would require the linked files (recorded signal) to be stored together with the preset.

**Comment by ost-ing** [comment]
Hi @FutureErik , this is functionality has already been described in https://github.com/mnemonicdevices/md001/issues/6 and is scheduled for the 0.4.0 milestone, so I'll close this ticket. You can track the other ticket for information on progress. Thanks!
