### ISSUE TITLE
Copy and paste settings between channels

### ISSUE THREAD

**Issue by cdromain** [mnemonicdevices/md001#37]
## Feature request & motivation
Instead of having to mult a Juniper signal to have several copies of it, would be great to be able to easily copy and paste channel settings from one channel to the other - both to have the same signal on several channels/outputs, but also as a quick way to use one channel settings as a starting point for a variation of it on another channel.

## Implementation
Will need to think about how this could be implemented interface-wise but using the channel menu could be simple enough.

**Comment by ost-ing** [comment]
Copy-Paste is a great idea, and will work quite easily with the 0.4.0 changes.

**Comment by cdromain** [comment]
Great, thanks Oliver - can't wait for this simple feature that will prove to be super useful I'm sure !
