### ISSUE TITLE
Random waveform shouldn't stop at the current value at max slew

### ISSUE THREAD

**Issue by ost-ing** [mnemonicdevices/md001#44]
**Describe the bug**
The random waveform stops at the current value rather than continuous moving between two values.

**To Reproduce**
Set the frequency very low (30mHz), set waveform to random, Morph/Slew to max

**Expected behavior**
The value should never stop at a given value, but always smoothly transition between them

**Comment by cdromain** [comment]
Looking forward to the fix and getting the random slewed behaviour I was looking for ! Ready to test when you are 😃 Thanks man !
