### ISSUE TITLE
Allow voltage controlled polarization.

### ISSUE THREAD

**Issue by CBluesF** [mnemonicdevices/md001#59]
**Describe the solution you'd like**
Expand range of amplitude values to +/- 100%, with negative values producing an inverted waveform, this would allow 4 quadrant multiplication/voltage controlled polarization.

**Describe alternatives you've considered**
Voltage control over the invert parameter could produce the same output with a threshold at 0v (i.e. control signal <0v results in inversion, >=0v leaves the signal as-is). This might even allow for more interesting modulation options, but to achieve the same result the amplifier would need to be controlled by a full-rectified version of the same modulator.

**Potential ramifications or implications**
Invert setting is less relevant, although if voltage controlled as mentioned above this could provide interesting options.

**Comment by ost-ing** [comment]
Thanks for the suggestion! I like the idea. I'll put some thought into it and see how I can fit it in the release schedule. Thanks!

**Comment by ost-ing** [comment]
Thanks @CBluesF - added to 0.5.0 ✅
