### ISSUE TITLE
Multiple state slots with performance like recall

### ISSUE THREAD

**Issue by ost-ing** [mnemonicdevices/md001#6]
**Is your feature request related to a problem? Please describe.**
As a user I would like to save state slots, so I can recall different states for different purposes. For example, one slot may be dedicated for recording on multiple channels, and another slot may be used for frequency modulation from a CV input.

Users have also suggested Banks of presets which could also be implemented and stored on the SD card

**Describe the solution you'd like**
It would be ideal to recall different save slots using the 8 LED buttons, from the "performance menu", so that users can change states on the fly in a performative way

**Describe alternatives you've considered**
N/A

**Potential ramifications or implications**
Will require a file-picker for choosing / saving states to the SD Card. This feature does not include multiple recorder slots at this time.

**Comment by lightshowlightshow** [comment]
I would also like to see a set of "bank" presets, where you can save a collection of states for all 8 channels for simultaneous recall. Both saved channel settings and bank settings.
