### ISSUE TITLE
Soft/hard sync

### ISSUE THREAD

**Issue by CBluesF** [mnemonicdevices/md001#62]
**Describe the solution you'd like**
Allow soft/hard sync with an external/internal trigger. When a trigger is detected, set the phase position to a fixed point.

**Describe alternatives you've considered**
Phase modulation can produce similar effects, but needs to be carefully dialled in. Clocking a channel in function generator mode produces a similar effect, but the clock needs to be constant rather than only at desired moments. 

**Potential ramifications or implications**
This would be incompatible with phase options/modulation as they stand. Could be an alternate mode for the phase screen or a mode like triggered mode.

**Comment by ost-ing** [comment]
@CBluesF , this is basically what is suggested here -  https://github.com/mnemonicdevices/md001/issues/70 , so I will close this ticket, please follow the other ticket for updates
