### ISSUE TITLE
Open source documentation & improvements

### ISSUE THREAD

**Issue by woowooly** [mnemonicdevices/md001#67]
**Describe the topic for investigation**
A clear and concise description of what the topic is.
Is it possible to bring up your Dokumentation to a level what evreybody can understand whats goin on?
Thanks

**Comment by cdromain** [comment]
Hey guys, discussed about it with @ostenning at Superbooth, I'd be glad to help flesh out & expand on the existing documentation to make it more intuitive and user-friendly. More examples, tips & tricks and suggestions of things to try would be nice as well ! Cheers

**Comment by ost-ing** [comment]
I will make the docs open-source for more user contributions, patch ideas etc

**Comment by woowooly** [comment]
Hi Oliver... Thank you.
Please bring the Quantizer up to date. I need it to pass, maybe only Note C E and B ... ...
Your work ist great and very cool.
Bg Lars


Von Outlook<http://aka.ms/weboutlook> gesendet.

________________________________
Von: Oliver ***@***.***>
Gesendet: Donnerstag, 11. Juli 2024 07:51
An: mnemonicdevices/md001 ***@***.***>
Cc: woowooly ***@***.***>; Author ***@***.***>
Betreff: Re: [mnemonicdevices/md001] Dokumentation (Issue #67)


I will make the docs open-source for more user contributions, patch ideas etc

**Comment by ost-ing** [comment]
> ...Please bring the Quantizer up to date

@woowooly The quantizer is being improved, it will be in the next release and will be out in the next week or so, you can pick a custom scale for each channel 👍

**Comment by ost-ing** [comment]
Documentation is now open-source and available at https://github.com/mnemonicdevices/docs . For any issues regarding documentation please open them there. Thanks
