### ISSUE TITLE
Offset doesn't affect the unipolar waveforms

### ISSUE THREAD

**Issue by CV-Gate** [mnemonicdevices/md001#68]
When I set a channel as "unipolar" and modify "offset," the percentage on the screen changes, but the waveform range is unaffected.

**To Reproduce**
Set a channel as "unipolar," choose a sin waveform, and manipulate the offset. Despite the percentage changes, the waveform stays in the same place.

**Expected behavior**
The affected waveform's offset must change when the offset is manipulated, even if it's unipolar. The waveform is expected to be limited, depending on the amp settings.

**Versioning
V 0.5.0

**Comment by ost-ing** [comment]
Thanks @CV-Gate I've just tested this and reproduced the bug. I'll have it fixed soon.

**Comment by ost-ing** [comment]
Fixed in 0.5.2
