### ISSUE TITLE
Select + channel buttons combo time setting

### ISSUE THREAD

**Issue by cdromain** [mnemonicdevices/md001#69]
## Feature request & motivation
When using the Select + channel buttons combo to select a channel, I way too often end up switching parameters when I actually want to switch channels (e.g. T&H instead of channel 1). What was a detail has become a bit irritating, given how much I use my beloved Juni 😃 (I know we can hold the Select button but that's not comfortable in my setup.)

## Implementation
A setting in the System settings would allow the user to modify (increase) the time available to push the channel button after the Select button. Seems like the default time we have to get the desired behavior is around 2 seconds. I think 3 to 5 would work better for my preferences.

**Comment by ost-ing** [comment]
Thanks for the feedback as usual! Yes, I will improve this for the next release

**Comment by CBluesF** [comment]
Just chiming in to add that it would be great to be able to reduce that time, too. I have the opposite problem, I usually use hold select + channel, and then when I try to choose a parameter change channel by mistake!

**Comment by ost-ing** [comment]
@CBluesF noted and thanks for the feedback - I've been working on this the last few days, it'll be in the next release
