### ISSUE TITLE
Amplitude & Offset units to become Voltage

### ISSUE THREAD

**Issue by ost-ing** [mnemonicdevices/md001#72]
The 16bit DAC allows for very fine grained voltage amplitude and offset control, but the current way (percentage) of changing amplitude is quite crude. Additionally the fine/grain control for amplitude seems overlooked.

Amplitude
- Voltage would be peak-to-peak and displayed as "Vpp", e.g. "10Vpp" would indicate -5V to +5V. 
- A Unipolar signal would be 5Vpp (0V to 5V). 
- Inverted waveforms would have a Voltage of "-Vpp".
- Course control would be 100mV steps, e.g. 4.1Vpp -> 4.2Vpp (pending testing)
- Fine control would be 10mV steps, e.g. 4.01Vpp -> 4.02Vpp

Offset
- Voltage would be displayed as "V", e.g. "1.1V".
- Course control would be 100mV steps, e.g. 4.1V -> 4.2V (pending testing)
- Fine control would be 10mV steps, e.g. 4.01V -> 4.02V

**Comment by MvKeinen** [comment]
That would be a great improvement! I'm looking forward to this!

**Comment by MvKeinen** [comment]
Maybe it would make sense to do the same with the offset parameter.

**Comment by ost-ing** [comment]
@MvKeinen absolutely - I've updated this issue

**Comment by ost-ing** [comment]
I've opted for 1mV steps being the smallest for now - accuracy depends on calibration but will need to do more testing, I may have to revise this

**Comment by CBluesF** [comment]
An option to adjust in 1V or 1/12V increments would be amazing for transposing incoming or random sequences.
