### ISSUE TITLE
Increased voltage range

### ISSUE THREAD

**Issue by cardinal-bin** [mnemonicdevices/md001#76]
**Describe the solution you'd like**
If the hardware allows, allow changing to +/- 10v signals.

**Describe alternatives you've considered**
A VCA can be used after Juniper's output to boost the signal.

**Potential ramifications or implications**
This is probably not possible, I assume that the 5v limit is set by the circuitry rather than software. But perhaps I'm wrong! If not though, just delete this suggestion.

**Comment by ost-ing** [comment]
Unfortunately the hardware is limited to -+5V, so this isn't feasible
