### ISSUE TITLE
The decay and skew parameters of the envelope waveform are flipped in 0.6.0

### ISSUE THREAD

**Issue by cardinal-bin** [mnemonicdevices/md001#82]
**Describe the bug**
Changing decay changes instead the skew, and vice versa.

**To Reproduce**
Try to alter either parameter

**Versioning (please complete the following information):**
 - Hardware revision 08
 - Firmware version 0.6.0
 - SD Card brand / model verbatim 32gb (as supplied)

**Comment by ost-ing** [comment]
@cardinal-bin nice catch. I'll release a bugfix 0.6.1 tomorrow.
