### ISSUE TITLE
Wave polarity is not in the channel parameters anymore

### ISSUE THREAD

**Issue by CV-Gate** [mnemonicdevices/md001#86]
As the title says, I cannot find the wave polarity parameter. It's not listed in the documentation either, so I'm not sure if it was intentionally removed or is in another place.

**Comment by ost-ing** [comment]
Hello @CV-Gate its now found under Amplitude settings: https://docs.mnemonicdevices.io/md001/signal_generation/primary_parameters.html#settings-1

**Comment by CV-Gate** [comment]
Thanks for your quick answer. I was looking there, but I didn't find it. I'll try again tomorrow.

Thank you!
